name: Generate doc1

on:
  push:
    branches:
      - main
    paths:
      - 'docs/doc1/source/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/doc1/source/**'
  
jobs:
  asciidoctor_job:
    runs-on: ubuntu-latest
    name: Build Asciidoctor
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: '3.0'

      - name: Install Asciidoctor and Asciidoctor diagram
        run: |
          gem install asciidoctor
          gem install asciidoctor-diagram

      - name: Install Mermaid
        run: npm install mermaid

      - name: Delete old documents
        run: rm -rf docs/doc1/build

      - name: Build AsciiDoc
        run: |
          mkdir -p docs/doc1/build
          asciidoctor -r asciidoctor-diagram -a allow-uri-read -o docs/doc1/build/index.html docs/doc1/source/index.adoc

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github@github.com'

      - name: Commit and push if changes detected
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Automated commit message"
          git push origin main

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Output-document
          path: docs/doc1/
